fsck: ignore missing "refs" directory for linked worktrees
It is reported that "git refs verify" would fail when encountering
worktrees created on Git v2.43.0 or older versions. These versions
don't automatically create the "refs" directory, causing the error:

    error: cannot open directory .git/worktrees/<worktree name>/refs:
    No such file or directory

Since 8f4c00de95 (builtin/worktree: create refdb via ref backend,
2024-01-08), we automatically create the "refs" directory for new
worktrees. However, the fsck code incorrectly assumes all linked
worktrees have this directory, thus introducing compatibility issue.

Check for ENOENT errno before reporting directory access errors for
linked worktrees to maintain backward compatibility.

Reported-by: Kristoffer Haugsbakk <code@khaugsbakk.name>
Signed-off-by: shejialuo <shejialuo@gmail.com>